openapi: 3.0.0
info:
  version: '2.16'
  title: Penpot RPC Add Team To Organization Move Project API
  description: Penpot RPC-style REST API for projects, files, pages, components, and design assets.
  x-api-id: penpot-rpc
  contact:
    url: https://community.penpot.app/
    name: Penpot Support
  x-humanURL: https://penpot.app/integrations-api
servers:
- url: https://design.penpot.app/api/main/methods
  description: MAIN API
tags:
- name: Move Project
paths:
  move-project:
    post:
      description: Move projects between teams
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: move-project
              type: object
              properties:
                teamId:
                  $ref: '#/components/schemas/Uuid'
                projectId:
                  $ref: '#/components/schemas/Uuid'
              required:
              - teamId
              - projectId
            example: '{"teamId":"5ab5eb30-5b3a-81d5-8008-2a395e1657b6","projectId":"5ab5eb30-5b3a-81d5-8008-2a395e1657b7"}'
      tags:
      - Move Project
components:
  schemas:
    Uuid:
      title: uuid
      description: UUID formatted string
      type: string
      format: uuid
