openapi: 3.0.0
info:
  version: '2.16'
  title: Penpot RPC Add Team To Organization Update Comment Thread API
  description: Penpot RPC-style REST API for projects, files, pages, components, and design assets.
  x-api-id: penpot-rpc
  contact:
    url: https://community.penpot.app/
    name: Penpot Support
  x-humanURL: https://penpot.app/integrations-api
servers:
- url: https://design.penpot.app/api/main/methods
  description: MAIN API
tags:
- name: Update Comment Thread
paths:
  update-comment-thread:
    post:
      description: null
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: update-comment-thread
              type: object
              properties:
                id:
                  $ref: '#/components/schemas/Uuid'
                isResolved:
                  type: boolean
                shareId:
                  $ref: '#/components/schemas/Uuid'
                  nullable: true
              required:
              - id
              - isResolved
            example: '{"id":"5ab5eb30-5b3a-81d5-8008-2a395e0e89e4","isResolved":false,"shareId":"5ab5eb30-5b3a-81d5-8008-2a395e0e89e5"}'
      tags:
      - Update Comment Thread
components:
  schemas:
    Uuid:
      title: uuid
      description: UUID formatted string
      type: string
      format: uuid
