openapi: 3.0.0
info:
  version: '2.16'
  title: Penpot RPC Add Team To Organization Get Team Deleted Files API
  description: Penpot RPC-style REST API for projects, files, pages, components, and design assets.
  x-api-id: penpot-rpc
  contact:
    url: https://community.penpot.app/
    name: Penpot Support
  x-humanURL: https://penpot.app/integrations-api
servers:
- url: https://design.penpot.app/api/main/methods
  description: MAIN API
tags:
- name: Get Team Deleted Files
paths:
  get-team-deleted-files:
    post:
      description: null
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: get-team-deleted-files
              type: object
              properties:
                teamId:
                  $ref: '#/components/schemas/Uuid'
              required:
              - teamId
            example: '{"teamId":"5ab5eb30-5b3a-81d5-8008-2a395c4636c8"}'
      tags:
      - Get Team Deleted Files
components:
  schemas:
    Uuid:
      title: uuid
      description: UUID formatted string
      type: string
      format: uuid
