openapi: 3.0.0
info:
  version: '2.16'
  title: Penpot RPC Add Team To Organization Update Profile API
  description: Penpot RPC-style REST API for projects, files, pages, components, and design assets.
  x-api-id: penpot-rpc
  contact:
    url: https://community.penpot.app/
    name: Penpot Support
  x-humanURL: https://penpot.app/integrations-api
servers:
- url: https://design.penpot.app/api/main/methods
  description: MAIN API
tags:
- name: Update Profile
paths:
  update-profile:
    post:
      description: null
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: update-profile
              type: object
              properties:
                fullname:
                  title: string
                  description: string
                  type: string
                  format: string
                lang:
                  type: string
                  maxLength: 8
                theme:
                  type: string
                  maxLength: 250
              required:
              - fullname
            example: '{"fullname":"qsfs"}'
      responses:
        default:
          description: A default response
          content:
            application/json:
              schema:
                title: Profile
                type: object
                properties:
                  id:
                    $ref: '#/components/schemas/Uuid'
                  fullname:
                    title: string
                    description: string
                    type: string
                    format: string
                  email:
                    $ref: '#/components/schemas/Email'
                  isActive:
                    $ref: '#/components/schemas/Boolean'
                  isBlocked:
                    $ref: '#/components/schemas/Boolean'
                  isDemo:
                    $ref: '#/components/schemas/Boolean'
                  isMuted:
                    $ref: '#/components/schemas/Boolean'
                  createdAt:
                    $ref: '#/components/schemas/Inst'
                  modifiedAt:
                    $ref: '#/components/schemas/Inst'
                  defaultProjectId:
                    $ref: '#/components/schemas/Uuid'
                  defaultTeamId:
                    $ref: '#/components/schemas/Uuid'
                  props:
                    title: ProfileProps
                    type: object
                    properties:
                      plugins:
                        type: object
                        properties:
                          ids:
                            type: array
                            items:
                              type: string
                          data:
                            type: object
                            additionalProperties:
                              type: object
                              properties:
                                pluginId:
                                  type: string
                                name:
                                  type: string
                                description:
                                  type: string
                                host:
                                  type: string
                                code:
                                  type: string
                                icon:
                                  type: string
                                permissions:
                                  type: array
                                  items:
                                    type: string
                                  uniqueItems: true
                              required:
                              - pluginId
                              - name
                              - host
                              - code
                              - permissions
                        required:
                        - ids
                        - data
                      renderer:
                        title: enum
                        type: string
                        enum:
                        - svg
                        - wasm
                      mcpEnabled:
                        $ref: '#/components/schemas/Boolean'
                      newsletterUpdates:
                        $ref: '#/components/schemas/Boolean'
                      newsletterNews:
                        $ref: '#/components/schemas/Boolean'
                      onboardingTeamId:
                        $ref: '#/components/schemas/Uuid'
                      onboardingViewed:
                        $ref: '#/components/schemas/Boolean'
                      v2InfoShown:
                        $ref: '#/components/schemas/Boolean'
                      welcomeFileId:
                        $ref: '#/components/schemas/Boolean'
                        nullable: true
                      releaseNotesViewed:
                        title: string
                        description: not whitespace string
                        type: string
                      notifications:
                        title: props-notifications
                        type: object
                        properties:
                          dashboardComments:
                            title: enum
                            type: string
                            enum:
                            - all
                            - partial
                            - none
                          emailComments:
                            title: enum
                            type: string
                            enum:
                            - all
                            - partial
                            - none
                          emailInvites:
                            title: enum
                            type: string
                            enum:
                            - all
                            - none
                        required:
                        - dashboardComments
                        - emailComments
                        - emailInvites
                      workspaceVisited:
                        $ref: '#/components/schemas/Boolean'
                required:
                - id
                - fullname
                - email
              example: '{"id":"5ab5eb30-5b3a-81d5-8008-2a395c5a541f","fullname":"vpvypcy","email":"aonraiw@example.net","isActive":false,"isBlocked":false,"isMuted":true,"modifiedAt":"2026-06-12T12:36:02.485180209Z","props":{"plugins":{"ids":["YijPh36q5Pb0RA388b5Mn","8s51k9e14","993W8elg5ChxUUF","duq7C79Q","","oWvu5","e9zD8wR3gPWn4wTB","1r77SZkoe0t02UTVxRS","h7w3nn5D9873qfJ195CcaAkU","SYwFQ955X8Rm6Atvih","3h83EzaM8Ie9XO1PpnLWpjWwlldM6e","Rupx54zF3VK6q","3137hWuass13T7jTcC6dB0T8","d93fQX51OM606R92Hl7Gg7x","4YTfWh","sG7bbGW99UkMcgm86EGiiUg6ZGuv","5aLb","aga1OIl2Lrwfrc7Ds00hei5Dm","Ug8cYGx6zUY","5WwqNY51BwTaDcL9DbK0J2","fDwdVdaW2xrNul306P3H52d","4VcD05L","aY3r9DUA433b16zqa27RD2X6","2jLu6NzKT5e92KGc","7l6r6ofFhu4MBpDsbju2Y5OG5ruhL","5hyjQ9bTlZGVU7E5WxTIg65w1","HJ11oFk1reH9s121ft1N7Qa49D4d7","U3v91AC247"],"data":{}},"welcomeFileId":null,"releaseNotesViewed":"yhygde"}}'
      tags:
      - Update Profile
components:
  schemas:
    Inst:
      title: instant
      type: string
      format: iso
    Boolean:
      title: boolean
      description: boolean
      type: boolean
    Uuid:
      title: uuid
      description: UUID formatted string
      type: string
      format: uuid
    Email:
      title: email
      description: string with valid email address
      type: string
      format: email
