openapi: 3.0.0
info:
  version: '2.16'
  title: Penpot RPC Add Team To Organization Update Font API
  description: Penpot RPC-style REST API for projects, files, pages, components, and design assets.
  x-api-id: penpot-rpc
  contact:
    url: https://community.penpot.app/
    name: Penpot Support
  x-humanURL: https://penpot.app/integrations-api
servers:
- url: https://design.penpot.app/api/main/methods
  description: MAIN API
tags:
- name: Update Font
paths:
  update-font:
    post:
      description: null
      deprecated: false
      requestBody:
        required: true
        content:
          application/json:
            schema:
              title: update-font
              type: object
              properties:
                teamId:
                  $ref: '#/components/schemas/Uuid'
                id:
                  $ref: '#/components/schemas/Uuid'
                name:
                  allOf:
                  - title: string
                    description: not whitespace string
                    type: string
              required:
              - teamId
              - id
              - name
            example: '{"teamId":"5ab5eb30-5b3a-81d5-8008-2a395c57ffe7","id":"5ab5eb30-5b3a-81d5-8008-2a395c583151","name":"tcpw"}'
      tags:
      - Update Font
components:
  schemas:
    Uuid:
      title: uuid
      description: UUID formatted string
      type: string
      format: uuid
